<a href="https://colab.research.google.com/github/Vamsh009/Quantum-Computing/blob/main/Superposition_Entanglement.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import numpy as np
qubit_0 = np.array([1,0])
H = (1/np.sqrt(2))*np.array([[1,1],[1,-1]])
superposition_state = np.dot(H , qubit_0)
print("Your Qubit in Superposition :")
print(superposition_state)

Your Qubit in Superposition :
[0.70710678 0.70710678]


In [7]:
import numpy as np
state_0 = np.array([1,0])
gate_X = np.array([[0,1],[1,0]])
identity = np.eye(2)
print(identity)
print(gate_X)


[[1. 0.]
 [0. 1.]]
[[0 1]
 [1 0]]


In [30]:
#Superposition


import numpy as np
state_0 = np.array([1,0])
gate_X = np.array([[0,1],[1,0]])
identity = np.eye(2)
H = (1/np.sqrt(2))*np.array([[1,1],[1,-1]])

def apply_gates(gate  , state):
  for gates in gate:
    state = np.dot(gates , state)
  return state
sup = apply_gates([H] , state_0)

def measurement(state):
  probs = np.abs(state)**2
  result = np.random.choice([0,1] , p = probs)
  return result
ans = measurement(sup)
print(ans)




1


In [29]:
#Entanglement Engine


def measurement(state):
  probs = np.abs(state)**2
  choices = ['00' , '01' , '10' , '11']
  result = np.random.choice(choices, p = probs)
  return result


import numpy as np
state_0 = np.array([1,0])
state_00 = np.kron(state_0 , state_0)
print(state_00)
H = (1/np.sqrt(2))*np.array([[1,1],[1,-1]])
I = np.eye(2)
CNOT = np.array([[1,0,0,0],[0,1,0,0],[0,0,0,1],[0,0,1,0]])
H_expanded = np.kron(H,I)
step1 =np.dot(H_expanded , state_00)
bell_state = np.dot(CNOT , step1)
results = { '00': 0 , '01': 0 , '10': 0 , '11': 0}

for _ in range(1000):
  measurement_result = measurement(bell_state)
  results[measurement_result] += 1

print("--- Entanglement Simulation Result ---")
for state , count in results.items():
  print(f"State {state} : {count} times")


[1 0 0 0]
--- Entanglement Simulation Result ---
State 00 : 484 times
State 01 : 0 times
State 10 : 0 times
State 11 : 516 times
